# Generated by Django 4.1 on 2022-08-31 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='user_interest1',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='student',
            name='user_interest2',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='student',
            name='user_interest3',
            field=models.CharField(max_length=200),
        ),
    ]
