# Generated by Django 4.0.6 on 2022-08-29 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_remove_student_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='profile_pic',
            field=models.ImageField(blank=True, default='http://127.0.0.1:8000/static/pfp_AKbu615.png', upload_to='icons'),
        ),
    ]
