# Generated by Django 4.0.6 on 2022-08-29 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_remove_student_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='profile_pic',
            field=models.ImageField(blank=True, default='../icons/racoon.png', upload_to=''),
        ),
    ]
