# Generated by Django 4.0.6 on 2022-08-09 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FinalizedMatching',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_user_1', models.IntegerField()),
                ('id_user_2', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PendingMatching',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_sender', models.IntegerField()),
                ('id_receiver', models.IntegerField()),
                ('isDenied', models.BooleanField(default=False)),
            ],
        ),
    ]
