# Generated by Django 4.0.6 on 2022-08-08 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_dept', models.CharField(choices=[('CSE', 'CSE'), ('MATH', 'MATH'), ('COGS', 'COGS'), ('POLI', 'POLI'), ('CHEM', 'CHEM')], max_length=10)),
                ('course_num', models.CharField(max_length=200, null=True)),
                ('prof', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
